### ISSUE TITLE
SageMaker studio example does not show new version of model package name

### ISSUE THREAD

**Issue by yycayley** [UpstageAI/aws-examples#10]
Hello Upstage team,
When clicking with open notebook in studio button in marketplace console, code indicates previous model package name like below :

[+] Notebook codes from opening SageMaker studio

<img width="937" alt="image" src="https://github.com/user-attachments/assets/e077922b-eb4d-4f97-a5fb-a053b1d7ae8b">

This leads to make error like :  _caller is not subscribed to the marketplace offering_
After changing model package name from [here](https://github.com/UpstageAI/aws-examples/blob/seungwon/add-embedding-output-example/sagemaker/Solar_Mini_Chat_Sagemaker_Marketplace.ipynb), we can resolve issue.

How can we know new model package version name with latest versions (240612.1)? Or could you please update new example notebook files to AWS? 
Thanks in advance.

-------
References
Solar Mini Chat - Quant : https://aws.amazon.com/marketplace/pp/prodview-5z6tpjgbfxbjg

**Comment by oesni** [comment]
Sorry for inconvenience, We have updated our notebook so that you can use our latest model packages.

You can check model package arn directly in aws console after subscribe model.

In `Sagemaker > Inference > Marketplace model packages` menu, you can find `AWS Marketplace Subscriptions` tab.

You can find the list of products you have subscribed and arn of each model.
![image](https://github.com/user-attachments/assets/62a9a82c-1481-4b3d-a393-7d2b03e9c5fd)
![image](https://github.com/user-attachments/assets/382b369c-d923-4dba-a443-82b621d09e3f)


Let us know if you have any further questions :) @yycayley
